import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT } from 'src/engine/metadata-modules/object-metadata/constants/standard-relation-field-properties.constant';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildComparableStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'comparable', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'comparable'>, FlatFieldMetadata> => ({
  // Base fields from BaseWorkspaceEntity
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Comparable-specific fields
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Name`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Comparable record Position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Comparable business fields
  adjustmentMeta: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'adjustmentMeta',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Adjustment Meta`),
      description: i18nLabel(
        msg`Raw transactional + property adjustment artifacts`,
      ),
      icon: 'IconJson',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  compAddress: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'compAddress',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Comp Address`),
      description: i18nLabel(msg`Street address of the comp`),
      icon: 'IconMapPin',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  descriptionAnalysis: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'descriptionAnalysis',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Description Analysis`),
      description: i18nLabel(
        msg`Listing-description analysis (description-analysis.md)`,
      ),
      icon: 'IconFileDescription',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  finalAdjustedPrice: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'finalAdjustedPrice',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Final Adjustment`),
      description: i18nLabel(msg`Final adjusted price (final_adjusted_price)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  imageAnalysis: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'imageAnalysis',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Image Analysis`),
      description: i18nLabel(msg`Photo analysis (image-analysis.md)`),
      icon: 'IconPhotoSearch',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  mlsNumber: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'mlsNumber',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`MLS Number`),
      description: i18nLabel(msg`MLS listing number`),
      icon: 'IconHash',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjAdu: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjAdu',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj ADU`),
      description: i18nLabel(msg`Property adjustment for ADU ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjAgeEffectiveAge: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjAgeEffectiveAge',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Age/effective age`),
      description: i18nLabel(
        msg`Property adjustment for Age/effective age ($)`,
      ),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjBasement: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjBasement',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Basement`),
      description: i18nLabel(msg`Property adjustment for Basement ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjBathrooms: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjBathrooms',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Bathrooms`),
      description: i18nLabel(msg`Property adjustment for Bathrooms ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjBedrooms: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjBedrooms',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Bedrooms`),
      description: i18nLabel(msg`Property adjustment for Bedrooms ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjCondition: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjCondition',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Condition`),
      description: i18nLabel(msg`Property adjustment for Condition ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjDesignStyle: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjDesignStyle',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Design/style`),
      description: i18nLabel(msg`Property adjustment for Design/style ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjEnergyEfficiency: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjEnergyEfficiency',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Energy efficiency`),
      description: i18nLabel(
        msg`Property adjustment for Energy efficiency ($)`,
      ),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjExternalObsolescence: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjExternalObsolescence',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj External obsolescence`),
      description: i18nLabel(
        msg`Property adjustment for External obsolescence ($)`,
      ),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjFireplace: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjFireplace',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Fireplace`),
      description: i18nLabel(msg`Property adjustment for Fireplace ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjFunctionalObsolescence: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjFunctionalObsolescence',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Functional obsolescence`),
      description: i18nLabel(
        msg`Property adjustment for Functional obsolescence ($)`,
      ),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjGarage: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjGarage',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Garage`),
      description: i18nLabel(msg`Property adjustment for Garage ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjGla: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjGla',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj GLA`),
      description: i18nLabel(msg`Property adjustment for GLA ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjHeatingCoolingHvac: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjHeatingCoolingHvac',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Heating/cooling (HVAC)`),
      description: i18nLabel(
        msg`Property adjustment for Heating/cooling (HVAC) ($)`,
      ),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjHoaFees: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjHoaFees',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj HOA fees`),
      description: i18nLabel(msg`Property adjustment for HOA fees ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjLocation: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjLocation',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Location`),
      description: i18nLabel(msg`Property adjustment for Location ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjLotSize: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjLotSize',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Lot Size`),
      description: i18nLabel(msg`Property adjustment for Lot Size ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjOutbuildings: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjOutbuildings',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Outbuildings`),
      description: i18nLabel(msg`Property adjustment for Outbuildings ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjPatioDeckPorch: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjPatioDeckPorch',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Patio/deck/porch`),
      description: i18nLabel(msg`Property adjustment for Patio/deck/porch ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjPoolSpa: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjPoolSpa',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Pool/spa`),
      description: i18nLabel(msg`Property adjustment for Pool/spa ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjQuality: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjQuality',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Quality`),
      description: i18nLabel(msg`Property adjustment for Quality ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjSolar: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjSolar',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj Solar`),
      description: i18nLabel(msg`Property adjustment for Solar ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pAdjView: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pAdjView',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`PAdj View`),
      description: i18nLabel(msg`Property adjustment for View ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reconMeta: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reconMeta',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Reconciliation Meta`),
      description: i18nLabel(
        msg`Per-comp reconciliation scores: similarity, adjustment_burden, recency, data_quality, composite, contribution`,
      ),
      icon: 'IconJson',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reconWeightPercent: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reconWeightPercent',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Recon Weight %`),
      description: i18nLabel(
        msg`Reconciliation weight percent (comps[].weight_percent)`,
      ),
      icon: 'IconPercentage',
      isNullable: true,
      settings: { decimals: 2 },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  salePrice: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'salePrice',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Sale Price`),
      description: i18nLabel(msg`Recorded sold price`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchRank: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchRank',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Search Rank`),
      description: i18nLabel(msg`Rank in sorted.csv`),
      icon: 'IconSortAscendingNumbers',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchScoring: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchScoring',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Search Scoring`),
      description: i18nLabel(
        msg`Per-comp similarity sub-scores from sorted.csv`,
      ),
      icon: 'IconChartRadar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  synthesis: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'synthesis',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Synthesis`),
      description: i18nLabel(msg`Combined per-comp synthesis (synthesis.md)`),
      icon: 'IconBinaryTree',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  transAdjConditions: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'transAdjConditions',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`TransAdj Conditions`),
      description: i18nLabel(msg`Transactional conditions step adjustment ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  transAdjExpenditures: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'transAdjExpenditures',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`TransAdj Expenditures`),
      description: i18nLabel(
        msg`Transactional expenditures step adjustment ($)`,
      ),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  transAdjFinancing: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'transAdjFinancing',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`TransAdj Financing`),
      description: i18nLabel(msg`Transactional financing step adjustment ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  transAdjRights: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'transAdjRights',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`TransAdj Rights`),
      description: i18nLabel(msg`Transactional rights step adjustment ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  transAdjTime: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'transAdjTime',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`TransAdj Time`),
      description: i18nLabel(msg`Transactional time step adjustment ($)`),
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relation fields
  reportNodes: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'reportNodes',
      label: i18nLabel(msg`Report Nodes`),
      description: i18nLabel(msg`Report nodes referencing this comparable`),
      icon: 'IconBinaryTree',
      isNullable: true,
      targetObjectName: 'reportNode',
      targetFieldName: 'comparable',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  property: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'property',
      label: i18nLabel(msg`Property`),
      description: i18nLabel(
        msg`Source property this comparable was built from`,
      ),
      icon: 'IconHome',
      isNullable: true,
      targetObjectName: 'property',
      targetFieldName: 'comparables',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'propertyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  selectedInCompsearch: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'selectedInCompsearch',
      label: i18nLabel(msg`Selected In Compsearch`),
      description: i18nLabel(msg`Compsearch that selected this comparable`),
      icon: 'IconListSearch',
      isNullable: true,
      targetObjectName: 'compsearch',
      targetFieldName: 'selected',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'selectedInCompsearchId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'timelineActivities',
      isSystemSideEffect: true,
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.timelineActivity
          .label,
      ),
      description: i18nLabel(msg`Timeline Activities linked to the comparable`),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT
        .timelineActivity.icon,
      isNullable: true,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'targetComparable',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
