import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationOnDeleteAction,
  RelationType,
} from 'twenty-shared/types';

import { STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT } from 'src/engine/metadata-modules/object-metadata/constants/standard-relation-field-properties.constant';
import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildAppraisalStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'appraisal', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'appraisal'>, FlatFieldMetadata> => ({
  // Base fields from BaseWorkspaceEntity
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Appraisal-specific fields
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Appraisal name`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Appraisal pipeline status`),
      icon: 'IconProgressCheck',
      isNullable: true,
      defaultValue: "'NEW'",
      options: [
        {
          id: '20202020-da2b-4a89-8c1c-eb66e8fec6e3',
          value: 'NEW',
          label: i18nLabel(msg`New`),
          position: 0,
          color: 'gray',
        },
        {
          id: '20202020-2d77-48c3-8b68-6480960b610b',
          value: 'SUBJECT_RESEARCH',
          label: i18nLabel(msg`Subject Research`),
          position: 1,
          color: 'blue',
        },
        {
          id: '20202020-8a47-4675-bbaa-5fa0dfc289db',
          value: 'COMP_SEARCH',
          label: i18nLabel(msg`Comp Search`),
          position: 2,
          color: 'turquoise',
        },
        {
          id: '4dbd4aee-9078-48e4-ad5e-986c7f9ab55a',
          value: 'COMP_COLLECT',
          label: i18nLabel(msg`Comp Collect`),
          position: 3,
          color: 'teal',
        },
        {
          id: '20202020-3b8e-4fea-aab5-424d49c7e781',
          value: 'COMP_SELECTION',
          label: i18nLabel(msg`Comp Selection`),
          position: 4,
          color: 'yellow',
        },
        {
          id: '20202020-8bff-45ee-b007-60dc76610900',
          value: 'ADJUSTMENTS_RECONCILIATION',
          label: i18nLabel(msg`Adjustments and Reconciliation`),
          position: 5,
          color: 'green',
        },
        {
          id: '20202020-57c2-4d1d-a20a-235123cba0f9',
          value: 'COMPLETE',
          label: i18nLabel(msg`Complete`),
          position: 6,
          color: 'purple',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  flowState: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'flowState',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Flow State`),
      description: i18nLabel(msg`Appraisal pipeline run state`),
      icon: 'IconActivityHeartbeat',
      isNullable: true,
      options: [
        {
          id: '20202020-bf17-4dab-b5e8-c80e84e347e9',
          value: 'RUNNING',
          label: i18nLabel(msg`Running`),
          position: 0,
          color: 'yellow',
        },
        {
          id: '20202020-ec8e-4416-9333-b385486e21cc',
          value: 'FAILED',
          label: i18nLabel(msg`Failed`),
          position: 1,
          color: 'red',
        },
        {
          id: '20202020-9bb4-4938-9b38-0e8baf6c3fbd',
          value: 'ABORTED',
          label: i18nLabel(msg`Aborted`),
          position: 2,
          color: 'gray',
        },
        {
          id: '20202020-1974-4b13-82d5-2fb42204ed40',
          value: 'DONE',
          label: i18nLabel(msg`Done`),
          position: 3,
          color: 'green',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  subjectAddress: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'subjectAddress',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Subject Address`),
      description: i18nLabel(msg`Street address of the subject property`),
      icon: 'IconMapPin',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  bedrooms: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'bedrooms',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Bedrooms`),
      description: i18nLabel(msg`Bedroom count`),
      icon: 'IconBed',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  bathrooms: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'bathrooms',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Bathrooms`),
      description: i18nLabel(msg`Bathroom count`),
      icon: 'IconBath',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  livingAreaGla: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'livingAreaGla',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Living Area GLA`),
      description: i18nLabel(msg`Gross living area in square feet`),
      icon: 'IconRuler',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  yearBuilt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'yearBuilt',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Year Built`),
      description: i18nLabel(msg`Year the subject was built`),
      icon: 'IconCalendar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  lotSize: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'lotSize',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Lot Size`),
      description: i18nLabel(msg`Lot size description`),
      icon: 'IconRuler2',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  style: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'style',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Style`),
      description: i18nLabel(msg`Architectural style`),
      icon: 'IconHome',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  quality: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'quality',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Quality`),
      description: i18nLabel(msg`Construction quality rating`),
      icon: 'IconStar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  conditionRating: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'conditionRating',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Condition Rating`),
      description: i18nLabel(msg`Overall condition rating`),
      icon: 'IconGauge',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  effectiveAge: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'effectiveAge',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Effective Age`),
      description: i18nLabel(msg`Effective age estimate`),
      icon: 'IconHourglass',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  garage: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'garage',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Garage`),
      description: i18nLabel(msg`Garage description`),
      icon: 'IconCar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  fireplace: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'fireplace',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Fireplace`),
      description: i18nLabel(msg`Fireplace description`),
      icon: 'IconFlame',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  heatingCooling: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'heatingCooling',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Heating Cooling`),
      description: i18nLabel(msg`Heating and cooling systems`),
      icon: 'IconTemperature',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  amenitiesOutbuildings: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'amenitiesOutbuildings',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Amenities Outbuildings`),
      description: i18nLabel(msg`Amenities and outbuildings`),
      icon: 'IconBuildingWarehouse',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  subjectView: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'subjectView',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Subject View`),
      description: i18nLabel(msg`View description`),
      icon: 'IconEye',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  transactionFha: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'transactionFha',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Transaction FHA`),
      description: i18nLabel(msg`Transaction or FHA notes`),
      icon: 'IconFileDollar',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  appraisalNotes: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'appraisalNotes',
      type: FieldMetadataType.RICH_TEXT,
      label: i18nLabel(msg`Appraisal Notes`),
      description: i18nLabel(msg`Free-form appraisal notes`),
      icon: 'IconNotes',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  images: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'images',
      type: FieldMetadataType.FILES,
      label: i18nLabel(msg`Images`),
      description: i18nLabel(msg`Uploaded images for the appraisal`),
      icon: 'IconPhoto',
      isNullable: true,
      settings: { maxNumberOfValues: 60 },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Appraisal record Position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  compsearch: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'compsearch',
      label: i18nLabel(msg`Compsearch`),
      description: i18nLabel(msg`Comp analysis for this appraisal`),
      icon: 'IconListSearch',
      isNullable: true,
      targetObjectName: 'compsearch',
      targetFieldName: 'appraisals',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'compsearchId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  report: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'report',
      label: i18nLabel(msg`Report`),
      description: i18nLabel(msg`Report for this appraisal`),
      icon: 'IconReportAnalytics',
      isNullable: true,
      targetObjectName: 'report',
      targetFieldName: 'appraisals',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'reportId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  reportLink: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'reportLink',
      type: FieldMetadataType.LINKS,
      label: i18nLabel(msg`Report Link`),
      description: i18nLabel(msg`Link to the generated report page for this appraisal`),
      icon: 'IconReportAnalytics',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  subjectProperty: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'subjectProperty',
      label: i18nLabel(msg`Subject Property`),
      description: i18nLabel(msg`The subject property of this appraisal`),
      icon: 'IconHome',
      isNullable: true,
      targetObjectName: 'property',
      targetFieldName: 'subjectOfAppraisals',
      settings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: RelationOnDeleteAction.SET_NULL,
        joinColumnName: 'subjectPropertyId',
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  timelineActivities: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'timelineActivities',
      isSystemSideEffect: true,
      label: i18nLabel(
        STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT.timelineActivity
          .label,
      ),
      description: i18nLabel(msg`Timeline Activities linked to the appraisal`),
      icon: STANDARD_RELATION_FIELD_PROPERTIES_BY_RELATION_OBJECT
        .timelineActivity.icon,
      isNullable: true,
      targetObjectName: 'timelineActivity',
      targetFieldName: 'targetAppraisal',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
