import { msg } from '@lingui/core/macro';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';

export const buildPropertyStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<
  CreateStandardFieldArgs<'property', FieldMetadataType>,
  'context'
>): Record<AllStandardObjectFieldName<'property'>, FlatFieldMetadata> => ({
  // Base fields from BaseWorkspaceEntity
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIEditable: false,
      defaultValue: 'now',
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIEditable: false,
      settings: { displayFormat: DateDisplayFormat.RELATIVE },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Property-specific fields
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Name`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Property record Position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIEditable: false,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  age: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'age',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Age`),
      description: i18nLabel(msg`Age`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  agentRemarks: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'agentRemarks',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Agent Remarks`),
      description: i18nLabel(msg`Agent Remarks`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  apxAboveGradeFin: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'apxAboveGradeFin',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Approx. Above-Grade Finished`),
      description: i18nLabel(msg`Approx. Above-Grade Finished`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  apxAboveGradeUnfin: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'apxAboveGradeUnfin',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Approx. Above-Grade Unfinished`),
      description: i18nLabel(msg`Approx. Above-Grade Unfinished`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  apxBelowGradeFin: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'apxBelowGradeFin',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Approx. Below-Grade Finished`),
      description: i18nLabel(msg`Approx. Below-Grade Finished`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  apxBelowGradeUnfin: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'apxBelowGradeUnfin',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Approx. Below-Grade Unfinished`),
      description: i18nLabel(msg`Approx. Below-Grade Unfinished`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  apxFinSqft: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'apxFinSqft',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Approx. Finished Sq Ft`),
      description: i18nLabel(msg`Approx. Finished Sq Ft`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  apxUnfinSqft: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'apxUnfinSqft',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Approx. Unfinished Sq Ft`),
      description: i18nLabel(msg`Approx. Unfinished Sq Ft`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  city: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'city',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`City`),
      description: i18nLabel(msg`City`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  class: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'class',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Property Class`),
      description: i18nLabel(msg`Property Class`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  closingDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'closingDate',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Closing Date`),
      description: i18nLabel(msg`Closing Date`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  concessions: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'concessions',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Concessions`),
      description: i18nLabel(msg`Concessions`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  construction: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'construction',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Construction`),
      description: i18nLabel(msg`Construction`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  cooling: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'cooling',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Cooling`),
      description: i18nLabel(msg`Cooling`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  county: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'county',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`County`),
      description: i18nLabel(msg`County`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  dom: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'dom',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Days on Market`),
      description: i18nLabel(msg`Days on Market`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  fencing: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'fencing',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Fencing`),
      description: i18nLabel(msg`Fencing`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  financingRemarks: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'financingRemarks',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Financing Remarks`),
      description: i18nLabel(msg`Financing Remarks`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  fireplace: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'fireplace',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Fireplace`),
      description: i18nLabel(msg`Fireplace`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  garageCapacity: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'garageCapacity',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Garage Capacity`),
      description: i18nLabel(msg`Garage Capacity`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  garageDimensions: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'garageDimensions',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Garage Dimensions`),
      description: i18nLabel(msg`Garage Dimensions`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  garageType: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'garageType',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Garage Type`),
      description: i18nLabel(msg`Garage Type`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  gradeSchool: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'gradeSchool',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Grade School`),
      description: i18nLabel(msg`Grade School`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  heating: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'heating',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Heating`),
      description: i18nLabel(msg`Heating`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  howSold: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'howSold',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`How Sold`),
      description: i18nLabel(msg`How Sold`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  jrHigh: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'jrHigh',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Junior High School`),
      description: i18nLabel(msg`Junior High School`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  kitchenFeatures: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'kitchenFeatures',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Kitchen Features`),
      description: i18nLabel(msg`Kitchen Features`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  landSize: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'landSize',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Land Size`),
      description: i18nLabel(msg`Land Size`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  landUse: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'landUse',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Land Use`),
      description: i18nLabel(msg`Land Use`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  level: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'level',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Level`),
      description: i18nLabel(msg`Level`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  lotFeatures: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'lotFeatures',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Lot Features`),
      description: i18nLabel(msg`Lot Features`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  lotLength: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'lotLength',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Lot Length`),
      description: i18nLabel(msg`Lot Length`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  lotWidth: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'lotWidth',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Lot Width`),
      description: i18nLabel(msg`Lot Width`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  numAcres: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'numAcres',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Number of Acres`),
      description: i18nLabel(msg`Number of Acres`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  numBaths: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'numBaths',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Bathrooms`),
      description: i18nLabel(msg`Bathrooms`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  numBeds: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'numBeds',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Bedrooms`),
      description: i18nLabel(msg`Bedrooms`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  parcelNumber: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'parcelNumber',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Parcel Number`),
      description: i18nLabel(msg`Parcel Number`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  pendingDate: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'pendingDate',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Pending Date`),
      description: i18nLabel(msg`Pending Date`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  photos: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'photos',
      type: FieldMetadataType.FILES,
      label: i18nLabel(msg`Photos`),
      description: i18nLabel(msg`Photos`),
      icon: 'IconPhoto',
      isNullable: true,
      settings: { maxNumberOfValues: 60 },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  remarks: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'remarks',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Remarks`),
      description: i18nLabel(msg`Remarks`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  roof: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'roof',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Roof`),
      description: i18nLabel(msg`Roof`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  salesHistory: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'salesHistory',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Sales History`),
      description: i18nLabel(
        msg`Sale/list/pending event history (array of date,event,price,pricePerSqFt)`,
      ),
      icon: 'IconHistory',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  parcelGeojson: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'parcelGeojson',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Parcel GeoJSON`),
      description: i18nLabel(msg`Parcel boundary geometry as GeoJSON`),
      icon: 'IconMap2',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  schoolDistrict: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'schoolDistrict',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`School District`),
      description: i18nLabel(msg`School District`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sewer: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sewer',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Sewer`),
      description: i18nLabel(msg`Sewer`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sourceId: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sourceId',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Source Id`),
      description: i18nLabel(msg`MLS number — dedupe key for property sync`),
      icon: 'IconId',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sprinkler: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sprinkler',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Sprinkler`),
      description: i18nLabel(msg`Sprinkler`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  srHigh: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'srHigh',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Senior High School`),
      description: i18nLabel(msg`Senior High School`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  state: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'state',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`State`),
      description: i18nLabel(msg`State`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Status`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  structureFeatures: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'structureFeatures',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Structure Features`),
      description: i18nLabel(msg`Structure Features`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  subdivision: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'subdivision',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Subdivision`),
      description: i18nLabel(msg`Subdivision`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  water: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'water',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Water`),
      description: i18nLabel(msg`Water`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  waterHeater: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'waterHeater',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Water Heater`),
      description: i18nLabel(msg`Water Heater`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  yearBuilt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'yearBuilt',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Year Built`),
      description: i18nLabel(msg`Year Built`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  zip: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'zip',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`ZIP Code`),
      description: i18nLabel(msg`ZIP Code`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  zoning: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'zoning',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Zoning`),
      description: i18nLabel(msg`Zoning`),
      icon: 'IconAbc',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  subjectOfAppraisals: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'subjectOfAppraisals',
      label: i18nLabel(msg`Subject Of Appraisals`),
      description: i18nLabel(msg`Appraisals where this is the subject property`),
      icon: 'IconFileDollar',
      isNullable: true,
      targetObjectName: 'appraisal',
      targetFieldName: 'subjectProperty',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  comparables: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'comparables',
      label: i18nLabel(msg`Comparables`),
      description: i18nLabel(msg`Comparables built from this property`),
      icon: 'IconGitCompare',
      isNullable: true,
      targetObjectName: 'comparable',
      targetFieldName: 'property',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  artifacts: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'artifacts',
      label: i18nLabel(msg`Artifacts`),
      description: i18nLabel(msg`Artifacts collected for this property`),
      icon: 'IconPaperclip',
      isNullable: true,
      targetObjectName: 'artifact',
      targetFieldName: 'property',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
