import { type FlatViewField } from 'src/engine/metadata-modules/flat-view-field/types/flat-view-field.type';
import {
  createStandardViewFieldFlatMetadata,
  type CreateStandardViewFieldArgs,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/view-field/create-standard-view-field-flat-metadata.util';

export const computeStandardAppraisalViewFields = (
  args: Omit<CreateStandardViewFieldArgs<'appraisal'>, 'context'>,
): Record<string, FlatViewField> => {
  return {
    allAppraisalsName: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'name',
        fieldName: 'name',
        position: 0,
        isVisible: true,
        size: 200,
      },
    }),
    allAppraisalsStatus: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'status',
        fieldName: 'status',
        position: 1,
        isVisible: true,
        size: 150,
      },
    }),
    allAppraisalsFlowState: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'flowState',
        fieldName: 'flowState',
        position: 2,
        isVisible: true,
        size: 150,
      },
    }),
    allAppraisalsCreatedBy: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'createdBy',
        fieldName: 'createdBy',
        position: 3,
        isVisible: true,
        size: 150,
      },
    }),
    allAppraisalsCreatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'createdAt',
        fieldName: 'createdAt',
        position: 4,
        isVisible: true,
        size: 150,
      },
    }),
    allAppraisalsUpdatedAt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'updatedAt',
        fieldName: 'updatedAt',
        position: 5,
        isVisible: true,
        size: 150,
      },
    }),
    allAppraisalsSubjectAddress: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'subjectAddress',
        fieldName: 'subjectAddress',
        position: 6,
        isVisible: true,
        size: 250,
      },
    }),
    allAppraisalsBedrooms: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'bedrooms',
        fieldName: 'bedrooms',
        position: 7,
        isVisible: true,
        size: 100,
      },
    }),
    allAppraisalsBathrooms: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'bathrooms',
        fieldName: 'bathrooms',
        position: 8,
        isVisible: true,
        size: 100,
      },
    }),
    allAppraisalsLivingAreaGla: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'livingAreaGla',
        fieldName: 'livingAreaGla',
        position: 9,
        isVisible: true,
        size: 130,
      },
    }),
    allAppraisalsYearBuilt: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'yearBuilt',
        fieldName: 'yearBuilt',
        position: 10,
        isVisible: true,
        size: 110,
      },
    }),
    allAppraisalsLotSize: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'lotSize',
        fieldName: 'lotSize',
        position: 11,
        isVisible: true,
        size: 130,
      },
    }),
    allAppraisalsStyle: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'style',
        fieldName: 'style',
        position: 12,
        isVisible: true,
        size: 130,
      },
    }),
    allAppraisalsQuality: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'quality',
        fieldName: 'quality',
        position: 13,
        isVisible: true,
        size: 130,
      },
    }),
    allAppraisalsConditionRating: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'conditionRating',
        fieldName: 'conditionRating',
        position: 14,
        isVisible: true,
        size: 130,
      },
    }),
    allAppraisalsEffectiveAge: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'effectiveAge',
        fieldName: 'effectiveAge',
        position: 15,
        isVisible: true,
        size: 130,
      },
    }),
    allAppraisalsGarage: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'garage',
        fieldName: 'garage',
        position: 16,
        isVisible: true,
        size: 130,
      },
    }),
    allAppraisalsFireplace: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'fireplace',
        fieldName: 'fireplace',
        position: 17,
        isVisible: true,
        size: 130,
      },
    }),
    allAppraisalsHeatingCooling: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'heatingCooling',
        fieldName: 'heatingCooling',
        position: 18,
        isVisible: true,
        size: 150,
      },
    }),
    allAppraisalsAmenitiesOutbuildings: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'amenitiesOutbuildings',
        fieldName: 'amenitiesOutbuildings',
        position: 19,
        isVisible: true,
        size: 170,
      },
    }),
    allAppraisalsSubjectView: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'subjectView',
        fieldName: 'subjectView',
        position: 20,
        isVisible: true,
        size: 130,
      },
    }),
    allAppraisalsTransactionFha: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'transactionFha',
        fieldName: 'transactionFha',
        position: 21,
        isVisible: true,
        size: 150,
      },
    }),
    allAppraisalsAppraisalNotes: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'appraisalNotes',
        fieldName: 'appraisalNotes',
        position: 22,
        isVisible: true,
        size: 200,
      },
    }),
    allAppraisalsImages: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'images',
        fieldName: 'images',
        position: 23,
        isVisible: true,
        size: 150,
      },
    }),
    allAppraisalsCompsearch: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'compsearch',
        fieldName: 'compsearch',
        position: 24,
        isVisible: true,
        size: 150,
      },
    }),
    allAppraisalsReport: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'report',
        fieldName: 'report',
        position: 25,
        isVisible: true,
        size: 150,
      },
    }),
    allAppraisalsReportLink: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'reportLink',
        fieldName: 'reportLink',
        position: 26,
        isVisible: true,
        size: 200,
      },
    }),
    allAppraisalsSubjectProperty: createStandardViewFieldFlatMetadata({
      ...args,
      objectName: 'appraisal',
      context: {
        viewName: 'allAppraisals',
        viewFieldName: 'subjectProperty',
        fieldName: 'subjectProperty',
        position: 27,
        isVisible: true,
        size: 150,
      },
    }),
  };
};
